project:
  type: website
  output-dir: docs

website:
  title: "Travis Anger"
  navbar:
    background: "#00688b"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Miscellaneous
        menu:
          - resume.qmd
          - projects.qmd
          - lang.qmd
          - research.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

