project:
  type: website
  output-dir: doc

website:
  title: "Travis Anger Web"
  navbar:
    background: "#00688b"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Resume
        menu:
          - resume.qmd
          - projects.qmd
          - prog_lang.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

